### ISSUE TITLE
Curious use of __dirname

### ISSUE THREAD

**Issue by isaacs** [captainsafia/giddy#7]
On [this line](https://github.com/captainsafia/giddy/blob/master/src/index.js#L41), you're checking if `__dirname + file` exists, but I think maybe you mean `path.resolve(file)` or `process.cwd() + '/' + file`.

`__dirname` is the directory that the module itself lives in, so something like `./node_modules/giddy/src`.

Could be I'm just misunderstanding what the code is trying to do, of course :)  Neat module, thanks for sharing it.

**Comment by captainsafia** [comment]
Ah nice catch! Yeah, this was totally the wrong coding. That line was intending to see if the file at user's current working directory was available to determine whether or not to `add/rm`. I'll  push a fix for this.

**Comment by captainsafia** [comment]
Closed via 0cea01d.
